amyloidase_base = {'P37840': 'alpha synucleine',
                   'P05067': 'Amyloid-beta precursor protein (AOI)',
                   'P42858': 'Huntingtin',
                   'P00441': 'Superoxide dismutase [Cu-Zn] (SOD1)',
                   'P10636': 'Microtubule-associated protein tau (ATau)',
                   'Q9UHD9': 'Ubiquilin-2',
                   'P02647': 'Apolipoprotein A-I',
                   'P02652': 'Apolipoprotein A-II',
                   'P06727': 'Apolipoprotein A-IV',
                   'P02655': 'Apolipoprotein C-II',
                   'P02656': 'Apolipoprotein C-III',
                   'P01034': 'Cystatin-C',
                   'P02671': 'Fibrinogen alpha chain',
                   'P06396': 'Gelsolin',
                   'P0CG04': 'Immunoglobulin lambda constant 1',
                   'A0A080YUZ8': 'Lysozyme',
                   'A0A080YUZ9': 'Lysozyme',
                   'H0YDZ2': 'Lysozyme',
                   'A0A087WT59': 'Transthyretin',
                   'A0A087WV45': 'Transthyretin',
                   'P02766': 'TTR protein',
                   'V9GZJ0': 'TTR protein',
                   'Q13736': 'TTR protein',
                   'Q13739': 'TTR protein',
                   'P61769': 'Beta-2-microglobulin (Ab2M)',
                   'O14776': 'Transcription elongation regulator 1 (CA150)',
                   'P01258': 'Calcitonin',
                   'P43235': 'Cathepsin K',
                   'Q15517': 'Corneodesmosin',
                   'G8JLG2': 'Corneodesmosin',
                   'Q2L6G8': 'Corneodesmosin',
                   'Q7Z560': 'Corneodesmosin',
                   'Q7Z559': 'Corneodesmosin',
                   'M1SWB8': 'Corneodesmosin',
                   'D2IYL2': 'Corneodesmosin',
                   'P47929': 'Galectin-7',
                   'P10997': 'Islet amyloid polypeptide (IAPP)',
                   'P01308': 'Insulin',
                   'P02788': 'Lactotransferrin (ALac)',
                   'Q08431': 'Lactadherin',
                   'A1E959': 'Odontogenic ameloblast-associated protein (ODAM)',
                   'P04637': 'Cellular tumor antigen p53',
                   'P05109': 'Protein S100-A8',
                   'P06702': 'Protein S100-A9',
                   'Q15582': 'Kerato-epithelin (TGFBI)',
                   'P07315': 'Gamma-crystallin C',
                   'P07320': 'Gamma-crystallin D',
                   'P22914': 'Gamma-crystallin S',
                   'Q06141': 'Regenerating islet-derived protein 3-alpha',
                   'P04279': 'Semenogelin-1',
                   'Q02383': 'Semenogelin-2',
                   'Q9Y287': 'Immature BRI2',
                   'P01275': 'Glucagon',
                   'P02533': 'Keratin CK14',
                   'P13647': 'Keratin CK5',
                   'P11686': 'Lung surfactant protein (SP-C)',
                   'P04156': 'Prion protein (PrP)',
                   'P0DJI8': 'Serum amyloid A (SAA)',
                   'P0DJI9': 'Serum amyloid A (SAA)',
                   }

additional_base = {'P26196': 'Probable ATP-dependent RNA helicase DDX6',
                   'P35637': 'RNA-binding protein FUS',
                   'P09651': 'Heterogeneous nuclear ribonucleoprotein A1 (HNRNPA1)',
                   'P22626': 'Heterogeneous nuclear ribonucleoprotein A2/B1 (HNRNPA2B1)',
                   'P28340': 'DNA polymerase delta catalytic subunit (POLD1)',
                   'Q13148': 'TAR DNA-binding protein 43 (TDP43)',
                   'P31483': 'Cytotoxic granule associated RNA binding protein TIA1',
                   'Q8NDV7': 'Trinucleotide repeat-containing gene 6A protein (TNRC6A)',
                   'P08621': 'U1 small nuclear ribonucleoprotein 70 kDa (U1-70k)',
                   'P40337': 'von Hippel-Lindau disease tumor suppressor (VHL)'
                  } 